# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

use_frameworks!

target 'EunomiaCocoapodiOSTests' do
	pod 'CocoaLumberjack', '~> 2.2.0'
	pod 'Eunomia', :path => '../'
end